
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/pieces.css

# scripts loaded in the end of the body
scripts:
- /js/pieces.js
