
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Analytical: /analytical
  Non-analytical: /non-analytical
  Archives: /archives
  About me: /about-me

# stylesheets loaded in the <head>
stylesheets:
- /css/pieces.css

# scripts loaded in the end of the body
scripts:
- /js/pieces.js
